default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: black_mamba
  password: black_mamba

development:
  <<: *default
  database: black_mamba_development

test:
  <<: *default
  database: black_mamba_test

production:
  <<: *default
  database: black_mamba_production
  username: black_mamba
  password: <%= ENV['BLACK_MAMBA_DATABASE_PASSWORD'] %>
